prefix = /usr
exec_prefix = /usr
sysconfdir = /etc
localstatedir = /var
sbindir = ${exec_prefix}/sbin
logdir = /var/log/freeradius
raddbdir = /etc/freeradius
radacctdir = ${logdir}/radacct

name = freeradius

confdir = ${raddbdir}
modconfdir = ${confdir}/mods-config
certdir = ${confdir}/certs
cadir   = ${confdir}/certs
run_dir = ${localstatedir}/run/${name}
db_dir = ${raddbdir}

libdir = /usr/lib/freeradius

pidfile = ${run_dir}/${name}.pid

max_request_time = 10
cleanup_delay = 0
max_requests = 65536
hostname_lookups = no

unlang {
}

log {
    destination = stdout
    colourise = yes
    stripped_names = no
    auth = no
    auth_badpass = no
    auth_goodpass = no
    msg_denied = "You are already logged in - access denied"
}

checkrad = ${sbindir}/checkrad

ENV {
}

security {
    user = freerad
    group = freerad
    allow_core_dumps = no
    max_attributes = 200
    reject_delay = 0
    status_server = yes
    require_message_authenticator = no
    limit_proxy_state = no
}

proxy_requests = yes
$INCLUDE proxy.conf

$INCLUDE clients.conf

thread pool {
    start_servers = 128
    max_servers = 512
    min_spare_servers = 32
    max_spare_servers = 64
    max_queue_size = 65536
    max_requests_per_server = 0
    auto_limit_acct = no
}

modules {
    $INCLUDE mods-enabled/
}

instantiate {
}

policy {
    $INCLUDE policy.d/
}

$INCLUDE sites-enabled/
