worker_processes auto;
worker_rlimit_nofile 65536;

events {
    worker_connections 16384;
    multi_accept on;
    use epoll;
}

stream {
    resolver 127.0.0.11 valid=5s ipv6=off;

    proxy_buffer_size 16k;

    upstream radius_auth {
        hash $remote_addr consistent;
        server freeradius-1:1812;
        server freeradius-2:1812;
        server freeradius-3:1812;
        server freeradius-4:1812;
        server freeradius-5:1812;
        server freeradius-6:1812;
        server freeradius-7:1812;
        server freeradius-8:1812;
    }

    upstream radius_acct {
        hash $remote_addr consistent;
        server freeradius-1:1813;
        server freeradius-2:1813;
        server freeradius-3:1813;
        server freeradius-4:1813;
        server freeradius-5:1813;
        server freeradius-6:1813;
        server freeradius-7:1813;
        server freeradius-8:1813;
    }

    server {
        listen 1812 udp reuseport;
        proxy_pass radius_auth;
        proxy_timeout 10s;
        proxy_responses 1;
    }

    server {
        listen 1813 udp reuseport;
        proxy_pass radius_acct;
        proxy_timeout 10s;
        proxy_responses 1;
    }
}
